services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_listings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - .env
      - DJANGO_DB_HOST=${DJANGO_DB_HOST} #loaded from .env file
      - DJANGO_DB_NAME=${DJANGO_DB_NAME} #loaded from .env file
      - DJANGO_DB_USER=${DJANGO_DB_USER} #loaded from .env file
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD} #loaded from .env file
      - DJANGO_REDIS_HOST=${DJANGO_REDIS_HOST} #loaded from .env file
      - DJANGO_REDIS_PORT=${DJANGO_REDIS_PORT} #loaded from .env file
      - DEBUG=True
    volumes:
      - .:/app


volumes:
  postgres_data:
  redis_data:
